name: torchquad
channels:
- conda-forge
dependencies:
- python=3.8
- numpy
- scipy
- matplotlib
- jupyter
- sympy
- pytorch
- torchvision
- scikit-learn
- scikit-image
- pandas
- seaborn
- ipywidgets
- nodejs
- pip
- pip:
  - torchquad
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-lsp
  - jupyterlab-toc
  - jupyterlab-widgets

